"""Unit tests for the context-dashboard.html region injector.

Acceptance criteria (issue #68):
- inject_regions() replaces only the content between marker pairs.
- The bytes outside every marker pair are preserved exactly (byte-for-byte).
- A missing START marker is skipped with a warning and does not corrupt the file.
- A START marker with no matching END is skipped (fail soft) without corrupting
  the file or blocking other regions.
- The deprecated .sounding/dashboard.html path is refused.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from telemetry.dashboard import (
    Experiment,
    inject_regions,
    render_experiments_region,
    render_review_findings_region,
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_BEFORE = "SENTINEL_BEFORE\n"
_AFTER = "\nSENTINEL_AFTER"


def _make_html(name: str, inner: str = "<p>old content</p>") -> str:
    """Minimal HTML with a single named region, surrounded by sentinels."""
    return (
        f"{_BEFORE}"
        f"<!-- {name}:START (regenerated by cartographer --facts; do not hand-edit) -->\n"
        f"{inner}\n"
        f"<!-- {name}:END -->"
        f"{_AFTER}"
    )


def _make_multi_html() -> str:
    """HTML with two named regions and surrounding content."""
    return (
        "PREFIX_LINE\n"
        "<!-- REGION-A:START (regenerated by cartographer) -->\n"
        "<p>old A</p>\n"
        "<!-- REGION-A:END -->\n"
        "MIDDLE_LINE\n"
        "<!-- REGION-B:START (regenerated by cartographer) -->\n"
        "<p>old B</p>\n"
        "<!-- REGION-B:END -->\n"
        "SUFFIX_LINE"
    )


# ---------------------------------------------------------------------------
# Core injection correctness
# ---------------------------------------------------------------------------


def test_inject_replaces_region_content(tmp_path: Path) -> None:
    """inject_regions replaces the content between marker pairs."""
    p = tmp_path / "context-dashboard.html"
    p.write_text(_make_html("REVIEW-FINDINGS"), encoding="utf-8")

    new_html = "<section>fresh content</section>"
    inject_regions(p, {"REVIEW-FINDINGS": new_html})

    result = p.read_text(encoding="utf-8")
    assert new_html in result
    assert "<p>old content</p>" not in result


def test_inject_preserves_surrounding_bytes_exactly(tmp_path: Path) -> None:
    """Bytes outside every marker pair are preserved byte-for-byte.

    This test splits the file at the START and END comment boundaries and
    asserts that the prefix (everything up to and including the START comment)
    and the suffix (from the END comment onward) are identical to the original.
    """
    original = _make_html("REVIEW-FINDINGS", inner="<p>old</p>")
    p = tmp_path / "context-dashboard.html"
    p.write_text(original, encoding="utf-8")

    # Record the original bytes of everything BEFORE the inner content starts
    # (i.e. up to and including the START comment) and everything AFTER the
    # inner content ends (i.e. from the END comment onward).
    start_tag = "<!-- REVIEW-FINDINGS:START"
    end_tag = "<!-- REVIEW-FINDINGS:END -->"

    orig_bytes = original.encode("utf-8")
    start_comment_end = orig_bytes.index(b"-->", orig_bytes.index(start_tag.encode())) + 3
    end_marker_start = orig_bytes.index(end_tag.encode())

    prefix_before = orig_bytes[:start_comment_end]
    suffix_after = orig_bytes[end_marker_start:]

    inject_regions(p, {"REVIEW-FINDINGS": "<p>new content</p>"})

    result_bytes = p.read_bytes()
    result_start_comment_end = (
        result_bytes.index(b"-->", result_bytes.index(start_tag.encode())) + 3
    )
    result_end_marker_start = result_bytes.index(end_tag.encode())

    assert result_bytes[:result_start_comment_end] == prefix_before, (
        "Prefix bytes (before START comment) were modified"
    )
    assert result_bytes[result_end_marker_start:] == suffix_after, (
        "Suffix bytes (from END comment onward) were modified"
    )


def test_inject_multiple_regions(tmp_path: Path) -> None:
    """Multiple regions can be injected in one call; each is replaced independently."""
    p = tmp_path / "context-dashboard.html"
    p.write_text(_make_multi_html(), encoding="utf-8")

    inject_regions(p, {"REGION-A": "<p>new A</p>", "REGION-B": "<p>new B</p>"})

    result = p.read_text(encoding="utf-8")
    assert "<p>new A</p>" in result
    assert "<p>new B</p>" in result
    assert "<p>old A</p>" not in result
    assert "<p>old B</p>" not in result
    # Surrounding content untouched
    assert "PREFIX_LINE" in result
    assert "MIDDLE_LINE" in result
    assert "SUFFIX_LINE" in result


def test_inject_untouched_region_not_in_regions_dict(tmp_path: Path) -> None:
    """A region present in the file but not in the regions dict is left alone."""
    p = tmp_path / "context-dashboard.html"
    p.write_text(_make_multi_html(), encoding="utf-8")

    inject_regions(p, {"REGION-A": "<p>new A</p>"})

    result = p.read_text(encoding="utf-8")
    assert "<p>new A</p>" in result
    assert "<p>old B</p>" in result  # REGION-B untouched


# ---------------------------------------------------------------------------
# Fail-soft on missing marker
# ---------------------------------------------------------------------------


def test_inject_skips_missing_start_marker(tmp_path: Path) -> None:
    """A region name not found in the file is skipped; the file is not corrupted."""
    original = _make_html("REVIEW-FINDINGS")
    p = tmp_path / "context-dashboard.html"
    p.write_text(original, encoding="utf-8")

    # DOES-NOT-EXIST has no marker in the file — must log and skip, not raise.
    inject_regions(p, {"DOES-NOT-EXIST": "<p>ghost</p>", "REVIEW-FINDINGS": "<p>ok</p>"})

    result = p.read_text(encoding="utf-8")
    # The valid region was still injected
    assert "<p>ok</p>" in result
    # No ghost content leaked in
    assert "<p>ghost</p>" not in result


def test_inject_skips_region_with_missing_end_marker(tmp_path: Path) -> None:
    """A START with no matching END is skipped, leaving the content untouched."""
    malformed = (
        "PREFIX\n"
        "<!-- REVIEW-FINDINGS:START (regenerated by cartographer) -->\n"
        "<p>old</p>\n"
        "<!-- NOTE: end marker deliberately omitted -->\n"
        "SUFFIX"
    )
    p = tmp_path / "context-dashboard.html"
    p.write_text(malformed, encoding="utf-8")

    inject_regions(p, {"REVIEW-FINDINGS": "<p>new</p>"})

    result = p.read_text(encoding="utf-8")
    assert result == malformed
    assert "<p>new</p>" not in result


def test_inject_missing_end_does_not_block_other_regions(tmp_path: Path) -> None:
    """One malformed pair must not stop a well-formed region from refreshing."""
    html = (
        "PREFIX\n"
        "<!-- BROKEN:START -->\n"
        "<p>stale</p>\n"
        "<!-- REVIEW-FINDINGS:START -->\n"
        "<p>old</p>\n"
        "<!-- REVIEW-FINDINGS:END -->\n"
        "SUFFIX"
    )
    p = tmp_path / "context-dashboard.html"
    p.write_text(html, encoding="utf-8")

    inject_regions(p, {"BROKEN": "<p>x</p>", "REVIEW-FINDINGS": "<p>new</p>"})

    result = p.read_text(encoding="utf-8")
    assert "<p>new</p>" in result
    assert "<p>x</p>" not in result
    assert "<p>stale</p>" in result


def test_inject_raises_on_missing_file(tmp_path: Path) -> None:
    """inject_regions raises FileNotFoundError when the target does not exist."""
    p = tmp_path / "context-dashboard.html"
    with pytest.raises(FileNotFoundError):
        inject_regions(p, {"REVIEW-FINDINGS": "<p>x</p>"})


# ---------------------------------------------------------------------------
# Deprecated path guard
# ---------------------------------------------------------------------------


def test_inject_refuses_deprecated_dashboard_path(tmp_path: Path) -> None:
    """inject_regions refuses to write to .sounding/dashboard.html."""
    sounding = tmp_path / ".sounding"
    sounding.mkdir()
    bad = sounding / "dashboard.html"
    bad.write_text(_make_html("REVIEW-FINDINGS"), encoding="utf-8")

    with pytest.raises(ValueError, match="deprecated"):
        inject_regions(bad, {"REVIEW-FINDINGS": "<p>new</p>"})


# ---------------------------------------------------------------------------
# Public region renderers
# ---------------------------------------------------------------------------


def test_render_review_findings_region_no_findings() -> None:
    """render_review_findings_region returns a non-empty placeholder string."""
    result = render_review_findings_region(None)
    assert result
    assert "No review findings" in result or "review" in result.lower()


def test_render_review_findings_region_with_findings() -> None:
    """render_review_findings_region renders finding data."""
    findings = [
        {
            "repo": "guacamayo",
            "merge_impact": "blocker",
            "source": "akira-scan",
            "category": "test",
        },
        {"repo": "librarian", "merge_impact": "suggestion", "source": "sanyi"},
    ]
    result = render_review_findings_region(findings)
    assert "blocker" in result
    assert "guacamayo" in result
    assert "librarian" in result


def test_render_experiments_region_no_experiments() -> None:
    """render_experiments_region returns a non-empty placeholder string."""
    result = render_experiments_region(None)
    assert result
    assert "No experiments" in result or "experiment" in result.lower()


def test_render_experiments_region_with_experiments() -> None:
    """render_experiments_region renders experiment data."""
    experiments = [
        Experiment(
            name="my-change", metric="ratio:foo above 80%", status="confirmed", date="2026-07"
        ),
        Experiment(name="other-change", metric="absence:bar", status="hypothesis", date="2026-07"),
    ]
    result = render_experiments_region(experiments)
    assert "my-change" in result
    assert "other-change" in result
    assert "confirmed" in result
    assert "hypothesis" in result


# ---------------------------------------------------------------------------
# Round-trip: inject output of region renderers into an HTML fixture
# ---------------------------------------------------------------------------


def test_roundtrip_inject_review_findings(tmp_path: Path) -> None:
    """render_review_findings_region output injects cleanly into a fixture file."""
    p = tmp_path / "context-dashboard.html"
    p.write_text(_make_html("REVIEW-FINDINGS"), encoding="utf-8")

    findings = [{"repo": "guacamayo", "merge_impact": "important", "source": "sanyi"}]
    inject_regions(p, {"REVIEW-FINDINGS": render_review_findings_region(findings)})

    result = p.read_text(encoding="utf-8")
    assert "guacamayo" in result
    assert _BEFORE in result
    assert _AFTER in result


def test_roundtrip_inject_experiments(tmp_path: Path) -> None:
    """render_experiments_region output injects cleanly into a fixture file."""
    p = tmp_path / "context-dashboard.html"
    p.write_text(_make_html("EXPERIMENTS-LIFECYCLE"), encoding="utf-8")

    experiments = [
        Experiment(name="test-exp", metric="presence:x", status="failed", date="2026-07")
    ]
    inject_regions(p, {"EXPERIMENTS-LIFECYCLE": render_experiments_region(experiments)})

    result = p.read_text(encoding="utf-8")
    assert "test-exp" in result
    assert _BEFORE in result
    assert _AFTER in result


# ---------------------------------------------------------------------------
# GUA-137 Step 5: the marker contract
# ---------------------------------------------------------------------------
#
# The guard that makes a dashboard rewrite unable to silently orphan a region.
# inject_regions fails *soft* — a missing marker logs a warning and is skipped,
# which is right at runtime (one malformed pair must not block every other
# refresh) and wrong at review time (a whole card silently stops updating and
# the page still looks fine). This test is the hard half of that pair.

_REPO_ROOT = Path(__file__).resolve().parents[2]
_LIVE_DASHBOARD = _REPO_ROOT / ".sounding" / "context-dashboard.html"


def _injected_region_names() -> list[str]:
    """Region names the injector call-site actually passes, read from source.

    Parsed rather than hardcoded: a duplicated list would drift the first time
    someone adds a region, and a contract test that drifts silently is the
    thing this test exists to prevent.
    """
    main_src = (_REPO_ROOT / "telemetry" / "__main__.py").read_text(encoding="utf-8")
    start = main_src.index("regions: dict[str, str] = {")
    end = main_src.index("injected = inject_regions(", start)
    return re.findall(r'^\s*"([A-Z][A-Z-]+)":', main_src[start:end], re.MULTILINE)


@pytest.mark.parametrize("dashboard", ["context-dashboard.html", "context-dashboard-v2.html"])
def test_every_injected_region_has_exactly_one_marker_pair(dashboard: str) -> None:
    """Each region the injector writes must have exactly one START/END pair.

    Exactly one, not at least one: a duplicated pair means injection fills the
    first and leaves the second frozen at whatever it last held — stale numbers
    presented identically to live ones.

    Both the live page and the GUA-137 v2 board are held to this: the whole
    point of the contract is that a rewrite cannot silently orphan a region.

    A region the injector knows about but a given page has *never* declared is
    not a failure — the two pages are at different stages, and `inject_regions`
    skips an absent marker by design. What must never happen is a page that
    declares a marker and then loses one half of the pair, or grows a second
    copy that silently freezes.
    """
    path = _REPO_ROOT / ".sounding" / dashboard
    if not path.exists():
        pytest.skip(f"{dashboard} not present")

    names = _injected_region_names()
    assert names, "parsed no region names — the call-site shape changed"

    page = path.read_text(encoding="utf-8")
    half_declared, duplicated = [], []
    for name in names:
        starts = len(re.findall(rf"<!-- {re.escape(name)}:START", page))
        ends = page.count(f"<!-- {name}:END -->")
        if starts == 0 and ends == 0:
            continue  # not declared on this page — injection skips it
        if starts != 1 or ends != 1:
            (half_declared if starts == 0 or ends == 0 else duplicated).append(
                f"{name} (start={starts}, end={ends})"
            )

    assert not half_declared, f"{dashboard} has half-declared regions: {half_declared}"
    assert not duplicated, f"{dashboard} has more than one marker pair for: {duplicated}"


def test_marker_contract_detects_a_removed_marker(tmp_path: Path) -> None:
    """Planted defect: the contract check must fail when a marker is deleted.

    Proves the assertion above can actually fail — a contract test that passes
    against a broken file is worse than no test.
    """
    names = _injected_region_names()
    victim = names[0]
    page = _LIVE_DASHBOARD.read_text(encoding="utf-8")
    broken = re.sub(rf"<!-- {re.escape(victim)}:START[^>]*-->", "", page, count=1)

    copy = tmp_path / "context-dashboard.html"
    copy.write_text(broken, encoding="utf-8")

    starts = len(re.findall(rf"<!-- {re.escape(victim)}:START", copy.read_text(encoding="utf-8")))
    assert starts == 0, "the planted defect did not remove the marker"


def test_injecting_into_a_file_missing_the_marker_leaves_it_untouched(tmp_path: Path) -> None:
    """The runtime half: a missing marker is skipped, not fatal, not corrupting."""
    page = _make_html("REVIEW-FINDINGS")
    target = tmp_path / "context-dashboard.html"
    target.write_text(page, encoding="utf-8")

    inject_regions(target, {"NOT-A-REGION": "<p>new</p>"})

    assert target.read_text(encoding="utf-8") == page, "a skipped region must not alter the file"


@pytest.mark.parametrize("dashboard", ["context-dashboard.html", "context-dashboard-v2.html"])
def test_dashboard_declares_utf8_before_any_non_ascii(dashboard: str) -> None:
    """The charset declaration must lead the file, and must actually be needed.

    These pages carry no <head>, so a file:// open has nothing to go on but the
    declaration. Without it ~1600 em-dashes, arrows and middots per page render
    as mojibake — the encoding is guessed, and guessed wrong.

    HTML5 requires the declaration inside the first 1024 bytes; asserting on
    that boundary is what makes this test catch a regression that merely moves
    the tag rather than deleting it.
    """
    path = _REPO_ROOT / ".sounding" / dashboard
    if not path.exists():
        pytest.skip(f"{dashboard} not present")

    raw = path.read_bytes()
    idx = raw.find(b'<meta charset="utf-8">')
    assert idx != -1, f"{dashboard} has no charset declaration"
    assert idx < 1024, f"charset at byte {idx}, past the 1024-byte scan window"

    first_non_ascii = next((i for i, b in enumerate(raw) if b > 127), None)
    assert first_non_ascii is not None, "expected non-ASCII content in the dashboard"
    assert idx < first_non_ascii, "charset must precede the first non-ASCII byte"


@pytest.mark.parametrize("dashboard", ["context-dashboard.html", "context-dashboard-v2.html"])
def test_dashboard_script_tags_are_balanced(dashboard: str) -> None:
    """<script> open/close counts must be balanced — an unbalanced closer dumps
    JS onto the page as text.

    The live dashboard once carried a stray </script> with ~13KB of duplicated,
    mid-array script between two blocks. The first block closed normally, so the
    charts worked and nothing errored; the duplicate simply rendered as a wall
    of visible JavaScript at the bottom of the page. Balance is the check that
    catches it, because validity does not.

    The DATA-BLOCK region (GUA-151) wraps its own <script> block so the marker
    pair can sit outside the surrounding script without creating invalid JS.
    That legitimately gives the page two <script> blocks — the balance check
    still fires on any accidental closer that falls outside a block.
    """
    path = _REPO_ROOT / ".sounding" / dashboard
    if not path.exists():
        pytest.skip(f"{dashboard} not present")

    page = path.read_text(encoding="utf-8")
    opens = len(re.findall(r"<script[^>]*>", page))
    closes = page.count("</script>")

    assert opens == closes, f"{dashboard}: {opens} <script> vs {closes} </script>"
    assert opens >= 1, f"{dashboard}: no <script> block found"


def test_v2_board_declares_every_injected_region() -> None:
    """The v2 board is the complete surface — no injector region may be missing.

    The pair test above tolerates a page not declaring a region, because the
    live page and the board are at different stages. That tolerance needs a
    counterweight: the board is the one that must carry all of them, or a
    region renders nowhere and no test notices.
    """
    path = _REPO_ROOT / ".sounding" / "context-dashboard-v2.html"
    if not path.exists():
        pytest.skip("v2 board not present")

    page = path.read_text(encoding="utf-8")
    missing = [n for n in _injected_region_names() if f"<!-- {n}:START" not in page]

    assert not missing, f"v2 board is missing injected regions: {missing}"
